### ISSUE TITLE
About the noise data when run design.py

### ISSUE THREAD

**Issue by takuyaliu** [MyNiuuu/VCSD#1]
Great work, thank you for sharing! But I met a question when I run the following commands to design the optimal curve under the visibility constraint, '/tempssd/OP/darkframes/npyfile' cann't be found. I run the code in Windows. Althrough I download all dataset and the sampled noise, I cann't find this path, I set the 'sample noise' as the noiseroot, it works, but I'm not sure whether it's the right choice.

So where could I find '/tempssd/OP/darkframes/npyfile'? And was my choice useful and reasonable?

Hope to receive your valuable feedback. Thank you for sharing again!

**Comment by MyNiuuu** [comment]
Thank you so much for being interested in our work! I am sorry that I forgot to change the path of sampled noise, and yes, the 'noiseroot' should be set to the path of dowloaded noise files, which is './sample_noise' by default. Thank you for the valuable feedback of our code!

**Comment by takuyaliu** [comment]
> Thank you so much for being interested in our work! I am sorry that I forgot to change the path of sampled noise, and yes, the 'noiseroot' should be set to the path of dowloaded noise files, which is './sample_noise' by default. Thank you for the valuable feedback of our code!

: ) Thanks for sharing and replying!
